### ISSUE TITLE
Escaped E<gt>s in https://metacpan.org/pod/distribution/XML-LibXML/lib/XML/LibXML/Parser.pod

### ISSUE THREAD

**Issue by shlomif** [shlomif/perl-XML-LibXML#26]
Hi @davorg ! See https://github.com/shlomif/perl-XML-LibXML/tree/fix-Egt-escapes-in-pod . Can you try fixing it? It does not happen with your change reverted. Thanks!

**Comment by davorg** [comment]
See #27

**Comment by shlomif** [comment]
@davorg : thanks! merged
