### ISSUE TITLE
pod missing again?

### ISSUE THREAD

**Issue by manwar** [shlomif/perl-XML-LibXML#28]
Looks like pod gone missing again as shown below?

          enable native perl UTF8
          running xml2-config...ok (2.9.1)
          Checking for ability to link against xml2...yes
          Checking if your kit is complete...
          Warning: the following files are missing in your kit:
                 lib/XML/LibXML/Attr.pod
                 lib/XML/LibXML/CDATASection.pod
                 lib/XML/LibXML/Comment.pod
                 lib/XML/LibXML/Common.pod
                 lib/XML/LibXML/Document.pod
                 lib/XML/LibXML/DocumentFragment.pod
                 lib/XML/LibXML/DOM.pod
                 lib/XML/LibXML/Dtd.pod
                 lib/XML/LibXML/Element.pod
                 lib/XML/LibXML/ErrNo.pod
                 lib/XML/LibXML/Error.pod
                 lib/XML/LibXML/InputCallback.pod
                 lib/XML/LibXML/Namespace.pod
                 lib/XML/LibXML/Node.pod
                 lib/XML/LibXML/Parser.pod
                 lib/XML/LibXML/Pattern.pod
                 lib/XML/LibXML/PI.pod
                 lib/XML/LibXML/Reader.pod
                 lib/XML/LibXML/RegExp.pod
                 lib/XML/LibXML/RelaxNG.pod
                 lib/XML/LibXML/SAX.pod
                 lib/XML/LibXML/SAX/Builder.pod
                 lib/XML/LibXML/Schema.pod
                 lib/XML/LibXML/Text.pod
                 lib/XML/LibXML/XPathContext.pod
                 lib/XML/LibXML/XPathExpression.pod
                 LibXML.pod
       Please inform the author. 
       Generating a Unix-style Makefile
       Writing Makefile for XML::LibXML
       Writing MYMETA.yml and MYMETA.json

**Comment by shlomif** [comment]
@manwar: this: 1. Can be fixed for future invocations using "make docs" 2. Doesn't happen with cpan -i. Thanks!

**Comment by manwar** [comment]
Thanks for the explanation. Closing the issue now.
