### ISSUE TITLE
Link to "XML::LibXML By Example"

### ISSUE THREAD

**Issue by Grinnz** [shlomif/perl-XML-LibXML#32]
I think it would be great to link from the XML::LibXML docs to [XML::LibXML By Example](http://grantm.github.io/perl-libxml-by-example), perhaps at the end of the DESCRIPTION section. I would send a PR but I don't understand how to edit the main module's docs.

**Comment by shlomif** [comment]
@Grinnz : hi! I think it is in https://github.com/shlomif/perl-XML-LibXML/blob/master/docs/libxml.dbk#L362 . Can you send me a PR for that? Thanks!

**Comment by shlomif** [comment]
@Grinnz : ping! Do you need anything?

**Comment by shlomif** [comment]
https://en.wikipedia.org/wiki/Signed_Sealed_Delivered in latest cpan rel. Thanks!
