### ISSUE TITLE
Bump minimum Perl version to 5.014

### ISSUE THREAD

**Issue by atoomic** [shlomif/perl-XML-LibXML#55]
After playing with GitHub CI via #54
I doubt that you can install the whole stack of dependencies for Perl < 5.014

view build run from: https://github.com/atoomic/perl-XML-LibXML/runs/1360811754?check_suite_focus=true

We should consider bumping the minimum Perl version requirement accordingly

**Comment by Grinnz** [comment]
Test::TrailingSpace is only used for author tests so has no bearing on the perl requirement for installation.

**Comment by Grinnz** [comment]
Specifically: https://github.com/shlomif/perl-XML-LibXML/blob/master/t/style-trailing-space.t

**Comment by Grinnz** [comment]
To be perfectly clear: this is a very high upriver module, which is proven to work back to Perl 5.8 (http://matrix.cpantesters.org/?dist=XML-LibXML+2.0206) so I would very much object to raising the minimum version without a good reason.

**Comment by atoomic** [comment]
perfect if this is only a author testing thing, this is fine, let's close it

**Comment by atoomic** [comment]
we should consider CI without author testing for older versions of Perl

**Comment by atoomic** [comment]
I was able to confirm by adjusting the CI workflow from #54 to run the tests without AUTHOR_TESTING and tweaking `t/pod-files-presence.t` that everything is fine

https://github.com/atoomic/perl-XML-LibXML/actions/runs/348435636
