### ISSUE TITLE
Source code on GitHub incomplete

### ISSUE THREAD

**Issue by jidanni** [shlomif/perl-XML-LibXML#85]
On the XML::LibXML::Node man page,
>       nextSibling
>             $nextnode = $node->nextSibling();
>           Returns the next sibling if any .
>                                          ^

I wanted to remove the space before that period, but couldn't find the source file here on GitHub to edit.

**Comment by shlomif** [comment]
@jidanni : hi. I think the POD documentation is generated from the DocBook file.
